<img src="https://github.com/idebtor/DSpy/blob/6b3676c3de29f85d2e7f30679676d1fd96d88b17/images/WelcomeToDataStructures.jpg?raw=true" width=1000>

---------


# PSet 4: Ch1-7 JSON

Honor Code: On my honour, I pledge that I have neither received nor provided improper assistance 
in the completion of this assignment. 
Signed: 박예겸 Student Number: 21600277

## JSON파일을 파이썬 객체화하기(디코딩, 역직렬화)

- `json.load()`: 파일에 있는 JSON 포맷 데이터를 Python 객체로 읽어오기 (역직렬화 혹은 디코딩이라고 부르기도 합니다)
- `json.loads()`: 메모리에 있는 JSON 형식의 문자열로 되어 있는 입력자료를 받아 파이썬 객체로 전환합니다.  

<img src="https://github.com/idebtor/DSpy/blob/b67467b971cf48c14faf7c8ebed7a94871dbb2ad/images/chap1/Chapter%201-25json_load.jpg?raw=true" width="100%">
<center>그림1. load() and loads() 비교</center>

## 파이썬 객체로 JSON파일 만들기(인코딩, 직렬화)

- `json.dump()`: Python객체를 파일에 저장할 때(직렬화, 인코딩) 사용합니다. 
- `json.dumps()`: Python객체를 문자열로 출력할 때 사용합니다. 

<img src="https://github.com/idebtor/DSpy/blob/b67467b971cf48c14faf7c8ebed7a94871dbb2ad/images/chap1/Chapter%201-27json_dump.jpg?raw=true" width="100%">

<center>그림2. dump() and dumps() 비교</center>

# JSON Exercise - JSON file

## Code 편집기로 작성한 `companies.json`작성하기

코드(텍스트) 편집기를 사용하여 아래의 내용을 가진 파일(`companies.json`)을 작성하십시오. 
```json
[
    {
        "name": "Big Corpration",
        "numberOfEmployee": 10000,
        "ceo": "June", 
        "rating": 3.9
    },
    {
        "name": "Small Start-up",
        "numberOfEmployee": 5, 
        "ceo": null, 
        "rating": 4.5
    }
]
```

## Code 편집기로 작성한 companies.json을 읽고 출력하기

- `with open()`을 사용하면, `close()`을 호출할 필요가 없습니다. 

__Sample Run:__

```json
[{'name': 'Big Corpration', 'numberOfEmployee': 10000, 'ceo': 'June', 'rating': 3.9}, {'name': 'Small Start-up', 'numberOfEmployee': 5, 'ceo': None, 'rating': 4.5}]
```

In [105]:
import json

with open('companies.json') as f:    
    companies = json.load(f)
    
print(companies)

[{'name': 'Big Corpration', 'numberOfEmployee': 10000, 'ceo': 'June', 'rating': 3.9}, {'name': 'Small Start-up', 'numberOfEmployee': 5, 'ceo': None, 'rating': 4.5}]


## 자료를 하나씩 출력하기

각 회사(`company`)별로 출력합니다

__Sample Run:__

```json
{'name': 'Big Corpration', 'numberOfEmployee': 10000, 'ceo': 'June', 'rating': 3.9}
{'name': 'Small Start-up', 'numberOfEmployee': 5, 'ceo': None, 'rating': 4.5}
```

In [106]:
for company in companies:
    print(company)

{'name': 'Big Corpration', 'numberOfEmployee': 10000, 'ceo': 'June', 'rating': 3.9}
{'name': 'Small Start-up', 'numberOfEmployee': 5, 'ceo': None, 'rating': 4.5}


## 자료를 정렬하고 읽기 쉽게 포맷하기
- 각 회사의 자료에서 `numberOfEmployee`를 삭제하십시오. 
- `indent = 2`를 추가하고 필요에 따라 `sorted_keys = True` 추가합니다. 
- 아래와 같이 출력하십시오. 

__Sample Run:__
```json
[
  {
    "ceo": "June",
    "name": "Big Corpration",
    "rating": 3.9
  },
  {
    "ceo": null,
    "name": "Small Start-up",
    "rating": 4.5
  }
]
```

In [107]:
for company in companies:
    del company['numberOfEmployee']

sorted = json.dumps(companies, indent = 2, sort_keys = True)
print(sorted)

[
  {
    "ceo": "June",
    "name": "Big Corpration",
    "rating": 3.9
  },
  {
    "ceo": null,
    "name": "Small Start-up",
    "rating": 4.5
  }
]


## 새로운 JSON 파일(`companies_new.json`)에 저장하기
아래와 같은 내용으로 JSON파일(`companies_new.json`)을 작성하십시오. 

__Sample Run:__ Expected JSON File
```json
[
  {
    "ceo": "June",
    "name": "Big Corpration",
    "rating": 3.9
  },
  {
    "ceo": null,
    "name": "Small Start-up",
    "rating": 4.5
  }
]
```
- 가독성(readability)를 높이기 위하여 `indent = 2`를 인자로 사용하는 것이 좋습니다. 
- `with open()`을 사용하면, `close()`을 호출할 필요가 없습니다. 

__Solution__

In [42]:
with open('companies_new.json','w') as f:
    json.dump(companies,f, indent=2,sort_keys=True)

## 위에서 작성한 파일을 읽고 확인하기

__Sample Run:__

```json
{'ceo': 'June', 'name': 'Big Corpration', 'rating': 3.9}
{'ceo': None, 'name': 'Small Start-up', 'rating': 4.5}
[
  {
    "ceo": "June",
    "name": "Big Corpration",
    "rating": 3.9
  },
  {
    "ceo": null,
    "name": "Small Start-up",
    "rating": 4.5
  }
]
```

In [108]:
with open('companies_new.json') as f:
    companies = json.load(f)

for company in companies:
    print(company)
    
print(json.dumps(companies, indent = 2, sort_keys = True))

{'ceo': 'June', 'name': 'Big Corpration', 'rating': 3.9}
{'ceo': None, 'name': 'Small Start-up', 'rating': 4.5}
[
  {
    "ceo": "June",
    "name": "Big Corpration",
    "rating": 3.9
  },
  {
    "ceo": null,
    "name": "Small Start-up",
    "rating": 4.5
  }
]



# JSON Exercise: Exchange Rate Extraction

지금까지 경험해 본 JSON과 파이썬 코딩을 활용하여, 실생활 데이터를 가지고 응용하는 문제를 다루어 보도록 하겠습니다. 

이제는 대부분의 자료 제공자들이 JSON 파일 형식으로 자료를 제공합니다. 여기 연습문제로 무료로 140 여개의 환율 정보를 제공하는 Website에서 JSON 파일로 원화(KRW)에 대한 각 국가의 환율 정보를 가져옵니다. 그러한 환율 정보 중에서 몇 개의 특정한 통화를 계산해보는 응용 문제를 시도해봅니다. 

## JSON 파일을 다운받아 파이썬 객체로 변환하기
- 파일을 읽을 때는 `load()`를 사용하고, 문자열(String)을 읽을 때는`loads()`를 사용합니다. 

In [109]:
import json
from urllib.request import urlopen

with urlopen("http://www.floatrates.com/daily/krw.json") as response:
    source = response.read()

rates = json.loads(source)

## 파이썬 객체로 변환한 것을 출력하기
- 가독성을 위해 `ident = 2`로 설정하는 것이 필요합니다. 

__Sample Run:__
```json
{
  "usd": {
    "code": "USD",
    "alphaCode": "USD",
    "numericCode": "840",
    "name": "U.S. Dollar",
    "rate": 0.00086484208312665,
    "date": "Sat, 4 Sep 2021 23:55:01 GMT",
    "inverseRate": 1156.2804580285
  },
  "eur": {
    "code": "EUR",
    "alphaCode": "EUR",
    "numericCode": "978",
    "name": "Euro",
  ...
}
```

In [110]:
print(json.dumps(rates,indent=2))

{
  "usd": {
    "code": "USD",
    "alphaCode": "USD",
    "numericCode": "840",
    "name": "U.S. Dollar",
    "rate": 0.00086024871297761,
    "date": "Tue, 7 Sep 2021 23:55:01 GMT",
    "inverseRate": 1162.4545145074
  },
  "eur": {
    "code": "EUR",
    "alphaCode": "EUR",
    "numericCode": "978",
    "name": "Euro",
    "rate": 0.00072558820750023,
    "date": "Tue, 7 Sep 2021 23:55:01 GMT",
    "inverseRate": 1378.1921889899
  },
  "gbp": {
    "code": "GBP",
    "alphaCode": "GBP",
    "numericCode": "826",
    "name": "U.K. Pound Sterling",
    "rate": 0.00062380494854346,
    "date": "Tue, 7 Sep 2021 23:55:01 GMT",
    "inverseRate": 1603.0651926294
  },
  "cad": {
    "code": "CAD",
    "alphaCode": "CAD",
    "numericCode": "124",
    "name": "Canadian Dollar",
    "rate": 0.0010843434617936,
    "date": "Tue, 7 Sep 2021 23:55:01 GMT",
    "inverseRate": 922.21702369642
  },
  "jpy": {
    "code": "JPY",
    "alphaCode": "JPY",
    "numericCode": "392",
    "name": "Japan

## 파이썬 객체 `rates`의 `type`, 자료(통화)의 수, 각 환율 자료 출력하기

__Sample Run:__
```
<class 'dict'>
149
{'code': 'USD', 'alphaCode': 'USD', 'numericCode': '840', 'name': 'U.S. Dollar', 'rate': 0.00086484208312665, 'date': 'Sat, 4 Sep 2021 23:55:01 GMT', 'inverseRate': 1156.2804580285}
{'code': 'EUR', 'alphaCode': 'EUR', 'numericCode': '978', 'name': 'Euro', 'rate': 0.00072856130060557, 'date': 'Sat, 4 Sep 2021 23:55:01 GMT', 'inverseRate': 1372.5680998549}
```

In [111]:
print(type(rates))
print(len(rates))
for rate in rates:
    print(rates[rate])

<class 'dict'>
149
{'code': 'USD', 'alphaCode': 'USD', 'numericCode': '840', 'name': 'U.S. Dollar', 'rate': 0.00086024871297761, 'date': 'Tue, 7 Sep 2021 23:55:01 GMT', 'inverseRate': 1162.4545145074}
{'code': 'EUR', 'alphaCode': 'EUR', 'numericCode': '978', 'name': 'Euro', 'rate': 0.00072558820750023, 'date': 'Tue, 7 Sep 2021 23:55:01 GMT', 'inverseRate': 1378.1921889899}
{'code': 'GBP', 'alphaCode': 'GBP', 'numericCode': '826', 'name': 'U.K. Pound Sterling', 'rate': 0.00062380494854346, 'date': 'Tue, 7 Sep 2021 23:55:01 GMT', 'inverseRate': 1603.0651926294}
{'code': 'CAD', 'alphaCode': 'CAD', 'numericCode': '124', 'name': 'Canadian Dollar', 'rate': 0.0010843434617936, 'date': 'Tue, 7 Sep 2021 23:55:01 GMT', 'inverseRate': 922.21702369642}
{'code': 'JPY', 'alphaCode': 'JPY', 'numericCode': '392', 'name': 'Japanese Yen', 'rate': 0.094734588344729, 'date': 'Tue, 7 Sep 2021 23:55:01 GMT', 'inverseRate': 10.555806674972}
{'code': 'AUD', 'alphaCode': 'AUD', 'numericCode': '036', 'name': 'A

## 환율 정보에서 `code`와 `rate`만 추출하여 출력하기 
__Sample Run:__
```
USD 0.00086484208312665
EUR 0.00072856130060557
GBP 0.00062543395312534
JPY 0.09507474341514
AUD 0.0011633915091951
...
```

In [112]:
for item in rates:
    code = rates[item]['code']
    rate = rates[item]['rate']
    print(code, rate)

USD 0.00086024871297761
EUR 0.00072558820750023
GBP 0.00062380494854346
CAD 0.0010843434617936
JPY 0.094734588344729
AUD 0.0011631982603228
CHF 0.00078855420624272
COP 3.2513069501533
BZD 0.0017235330115543
GNF 8.3694939361587
SLL 8.8445192676703
KES 0.093971747330519
AED 0.0031458180338181
PHP 0.043192181334159
ILS 0.0027575518835112
MRO 0.031192581970241
BOB 0.005902549287063
GYD 0.17889204225869
RWF 0.86299370491516
MZN 0.054815278543352
UGX 3.0216732493426
CNY 0.005561077716566
SAR 0.0032263367920917
MYR 0.0035682074288339
KZT 0.36657133209901
TJS 0.0097168148045556
AFN 0.075955624571489
NAD 0.012353613171152
SYP 2.1816480860254
TOP 0.001922947543212
VUV 0.094804801235239
IDR 12.21447396309
TND 0.0023810819904794
XOF 0.47613312091382
UAH 0.022998025264125
ETB 0.039050980060122
XCD 0.0023176148222649
LAK 8.2016845339301
BWP 0.0094389158610852
KWD 0.00025809462430035
CZK 0.018434536547324
PGK 0.0030169373973098
RSD 0.084990038740583
GMD 0.04452343032705
AWG 0.0015477072119931
AOA 0.5

## `code`를 key, `rate`를 value로 하는 dict type의 `krw_rates` 만들기 
- 위의 코드를 수정하여 새로운 dict type의 객체 `krw_rates`를 만들어 `key`로 `rate`를 쉽게 찾는데 활용하려고 합니다. 
- 즉 `krw_rates['USD']`의 형식을 사용하여 환율 정보를 쉽게 접근할 수 있도록 하는 작업입니다.
- 다른 말로, 위에서 출력해본 `code, rate` 정보를 모두 `krw_rates`에 저장하는 것입니다. 

__Sample Run:__
```
0.00086484208312665
0.00072856130060557
0.09507474341514
0.001084071583917
```

In [119]:
krw_rates = dict()   # empty name in dict type 

for item in rates:
    code = rates[item]['code']
    rate = rates[item]['rate']
    krw_rates[code] = rate

print('USD:', krw_rates['USD']) 
print('EUR:', krw_rates['EUR'])
print('JPY:', krw_rates['JPY'])
print('CAD:', krw_rates['CAD'])

USD: 0.00086024871297761
EUR: 0.00072558820750023
JPY: 0.094734588344729
CAD: 0.0010843434617936


## 환율 계산 하기 
거의 다 했습니다. 이제 환율을 계산해봅니다. 여기서 제공되는 환율은 Korean Won(KRW)으로 1원에 대한 다른 통화의 가격입니다. 그러므로, 대개 숫자가 낮은 값으로 출력됨으로, 1000원에 대한 환율을 계산하여 봅시다. 
- `krw_rates[]`로 출력되는 값들은 모두 문자열(`str`) 타입이므로 `float()`로 변환하는 것이 필요합니다. 

__Sample Run:__
```
0.86484208312665
0.72856130060557
95.07474341513999
1.084071583917
```

In [120]:
#print(type(krw_rates['USD']))
print(krw_rates['USD']*1000) 
print(krw_rates['EUR']*1000)
print(krw_rates['JPY']*1000)
print(krw_rates['CAD']*1000)

0.86024871297761
0.72558820750023
94.734588344729
1.0843434617936


## 환율 정보에서 `date`를 추출하여 `krw_rates`에 추가하기 
- 환율 정보에서 빼놓을 수 없는 정보는 `date`입니다. `rate`와 더불어 `date`정보를 추가하려고 합니다. `krw_rates`의 `key`는 변함없이 각 통화 `code`값들(e.g. 'USD', 'EUR', etc.)이지만, `value`로 `rate`뿐만 아니라 `date`를 포함하여 정보를 유지관리하고 보호하려고 합니다. 다음과 같은 dict type을 만들려고 하는 것입니다. 이것을 어떻게 구현할 수 있겠습니까?  

```
{
  'USD': ('Sat, 4 Sep 2021 23:55:01 GMT', '0.00086484208312665'), 
  'EUR': ('Sat, 4 Sep 2021 23:55:01 GMT', '0.00072856130060557'),
 ...
}
```
값이 여러 개일 경우에는 list, tuple, dict types을 사용하여 하나로 묶어야 합니다. 자료를 수정하지 아니하도록 여기서는 tuple을 사용하도록 합니다.

__Sample Run:__
```
Sat, 4 Sep 2021 23:55:01 GMT 0.86484208312665
Sat, 4 Sep 2021 23:55:01 GMT 0.72856130060557
Sat, 4 Sep 2021 23:55:01 GMT 95.07474341513999
Sat, 4 Sep 2021 23:55:01 GMT 1.084071583917
```

In [121]:
krw_rates = dict()   # empty name in dict type 

for name in rates:
    date = rates[name]['date']
    code = rates[name]['code']
    rate = rates[name]['rate']
    krw_rates[code] = (date,rate)
    
print(krw_rates['USD'][0],krw_rates['USD'][1]*1000) 
print(krw_rates['EUR'][0],krw_rates['EUR'][1]*1000)
print(krw_rates['JPY'][0],krw_rates['JPY'][1]*1000)
print(krw_rates['CAD'][0],krw_rates['CAD'][1]*1000)

Tue, 7 Sep 2021 23:55:01 GMT 0.86024871297761
Tue, 7 Sep 2021 23:55:01 GMT 0.72558820750023
Tue, 7 Sep 2021 23:55:01 GMT 94.734588344729
Tue, 7 Sep 2021 23:55:01 GMT 1.0843434617936


--------
슬기로운 자는 재앙을 보면 숨어 피하여도 어리석은 자들은 나가다가 해를 받느니라. 
잠언22:3, 27:12